import glob
Import('env et_enable')

# Loop over libraries, building each
this_env=env.Clone()
this_env.Prepend(LIBS="libbdxRecoExt") 
this_env.Prepend(LIBS="libbdxReco")

this_env.AppendUnique(LIBS='cMsg')
this_env.AppendUnique(LIBS='cMsgxx')
this_env.AppendUnique(LIBS='cMsgRegex')
this_env.AppendUnique(LIBS='RootSpy')

if (et_enable):
    this_env.Prepend(LIBS="libet")

progs=['bdxReco']
for prog in progs:
    src =Glob(prog+'/*.cc')
    this_env.Program(source=src,target='#/bin/'+prog)	

