import glob
from utils import *
Import('env mc_enable')

# Loop over libraries, building each
libs=['EventBuilder','IntVeto','ExtVeto','Calorimeter','Paddles','TT','EPICS','system','DAQ','MC']
if (mc_enable):
	libs=['EventBuilder','IntVeto','ExtVeto','Calorimeter','Paddles','TT','EPICS','system','DAQ','MC']
else:
	libs=['EventBuilder','IntVeto','ExtVeto','Calorimeter','Paddles','TT','EPICS','system','DAQ']
	
src = []
for lib in libs:
	reldir = str(lib)
	absdir = Dir('#/src/libraries/'+reldir).srcnode().abspath	
	AddROOTdict(env,reldir,absdir)
	src = src+Glob(lib+'/*.cc')

env.SharedLibrary(source=src,target='#/lib/bdxReco')


