Import('env')

# Loop over libraries, building each
libs=['IntVeto','ExtVeto','Calorimeter','Paddles','TT','system','DAQ','MC']

for lib in libs:
    src =Glob(lib+'/*.cc')
    env.Library(source=src,target='#/lib/'+lib)
Return('libs')