#include <dlfcn.h>
#include <iostream>
#include <string>
using namespace std;
static string macro_data=""
"// hnamepath: /CalorimeterHits/hCaloHitE_allTrg_s0_x0_y0\n"
"// hnamepath: /CalorimeterHits/hCaloHitE_allTrg_s0_x1_y0\n"
"\n"
"// hnamepath: /CalorimeterHits/hCaloHitE_rndmTrg_s0_x0_y0\n"
"// hnamepath: /CalorimeterHits/hCaloHitE_rndmTrg_s0_x1_y0\n"
"\n"
"void aa()\n"
"\n"
"{\n"
"\n"
"	TDirectory *dir = (TDirectory*) gDirectory->FindObjectAny(\"CalorimeterHits\");\n"
"	if (dir) dir->cd();\n"
"\n"
"	TH1D *hCaloHitE_allTrg_s0_x0_y0 = 0;\n"
"	TH1D *hCaloHitE_allTrg_s0_x1_y0 = 0;\n"
"\n"
"	TH1D *hCaloHitE_rndmTrg_s0_x0_y0 = 0;\n"
"	TH1D *hCaloHitE_rndmTrg_s0_x1_y0 = 0;\n"
"\n"
"	/*Top-bottom*/\n"
"	TH1D *hCaloHitE_Trg0_s0_x0_y0 = 0;\n"
"	TH1D *hCaloHitE_Trg0_s0_x1_y0 = 0;\n"
"\n"
"	/*Front-back*/\n"
"	TH1D *hCaloHitE_Trg3_s0_x0_y0 = 0;\n"
"	TH1D *hCaloHitE_Trg3_s0_x1_y0 = 0;\n"
"\n"
"	hCaloHitE_allTrg_s0_x0_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_allTrg_s0_x0_y0\");\n"
"	hCaloHitE_rndmTrg_s0_x0_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_rndmTrg_s0_x0_y0\");\n"
"	hCaloHitE_Trg0_s0_x0_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_Trg0_s0_x0_y0\");\n"
"	hCaloHitE_Trg3_s0_x0_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_Trg3_s0_x0_y0\");\n"
"\n"
"	hCaloHitE_allTrg_s0_x1_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_allTrg_s0_x1_y0\");\n"
"	hCaloHitE_rndmTrg_s0_x1_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_rndmTrg_s0_x1_y0\");\n"
"	hCaloHitE_Trg0_s0_x1_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_Trg0_s0_x1_y0\");\n"
"	hCaloHitE_Trg3_s0_x1_y0 = (TH1D*) gDirectory->FindObjectAny(\"hCaloHitE_Trg3_s0_x1_y0\");\n"
"\n"
"	if (gPad == NULL) {\n"
"		TCanvas *c1 = new TCanvas(\"cCaloHits\");\n"
"		c1->cd(0);\n"
"		c1->Draw();\n"
"		c1->Update();\n"
"	}\n"
"\n"
"	if (!gPad) return;\n"
"	TCanvas *c1 = gPad->GetCanvas();\n"
"	c1->Divide(2, 2);\n"
"	c1->cd(1)->SetLogy();\n"
"	if (hCaloHitE_allTrg_s0_x0_y0 != 0) {\n"
"		hCaloHitE_allTrg_s0_x0_y0->Draw();\n"
"		if (hCaloHitE_rndmTrg_s0_x0_y0 != 0) {\n"
"			hCaloHitE_rndmTrg_s0_x0_y0->SetLineColor(2);\n"
"			hCaloHitE_rndmTrg_s0_x0_y0->Draw(\"SAMES\");\n"
"		}\n"
"\n"
"		if (hCaloHitE_Trg0_s0_x0_y0 != 0) {\n"
"			hCaloHitE_Trg0_s0_x0_y0->SetLineColor(3);\n"
"			hCaloHitE_Trg0_s0_x0_y0->Draw(\"SAMES\");\n"
"		}\n"
"\n"
"		if (hCaloHitE_Trg3_s0_x0_y0 != 0) {\n"
"			hCaloHitE_Trg3_s0_x0_y0->SetLineColor(4);\n"
"			hCaloHitE_Trg3_s0_x0_y0->Draw(\"SAMES\");\n"
"		}\n"
"\n"
"	}\n"
"\n"
"	c1->cd(2)->SetLogy();\n"
"	if (hCaloHitE_allTrg_s0_x1_y0 != 0) {\n"
"			hCaloHitE_allTrg_s0_x1_y0->Draw();\n"
"			if (hCaloHitE_rndmTrg_s0_x1_y0 != 0) {\n"
"				hCaloHitE_rndmTrg_s0_x1_y0->SetLineColor(2);\n"
"				hCaloHitE_rndmTrg_s0_x1_y0->Draw(\"SAMES\");\n"
"			}\n"
"\n"
"			if (hCaloHitE_Trg0_s0_x1_y0 != 0) {\n"
"				hCaloHitE_Trg0_s0_x1_y0->SetLineColor(3);\n"
"				hCaloHitE_Trg0_s0_x1_y0->Draw(\"SAMES\");\n"
"			}\n"
"\n"
"			if (hCaloHitE_Trg3_s0_x1_y0 != 0) {\n"
"				hCaloHitE_Trg3_s0_x1_y0->SetLineColor(4);\n"
"				hCaloHitE_Trg3_s0_x1_y0->Draw(\"SAMES\");\n"
"			}\n"
"\n"
"		}\n"
"}\n"
;
class CalorimeterHits_JLabFlux_rootspy_class{
   public:
   typedef void rmfcn(string, string, string);
   CalorimeterHits_JLabFlux_rootspy_class(){
      rmfcn* fcn = (rmfcn*)dlsym(RTLD_DEFAULT, "REGISTER_ROOTSPY_MACRO");
      if(fcn) (*fcn)("CalorimeterHits_JLabFlux","/", macro_data);
   }
};
static CalorimeterHits_JLabFlux_rootspy_class tmp;