/********************************************************************
* src/users/andrea/janaview/jv_mainframe_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/users/andrea/janaview/jv_mainframe_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablejv_mainframe_Dict();
extern void G__cpp_setup_inheritancejv_mainframe_Dict();
extern void G__cpp_setup_typetablejv_mainframe_Dict();
extern void G__cpp_setup_memvarjv_mainframe_Dict();
extern void G__cpp_setup_globaljv_mainframe_Dict();
extern void G__cpp_setup_memfuncjv_mainframe_Dict();
extern void G__cpp_setup_funcjv_mainframe_Dict();
extern void G__set_cpp_environmentjv_mainframe_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/users/andrea/janaview/jv_mainframe.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__jv_mainframe_DictLN_TClass;
extern G__linked_taginfo G__jv_mainframe_DictLN_TBuffer;
extern G__linked_taginfo G__jv_mainframe_DictLN_TMemberInspector;
extern G__linked_taginfo G__jv_mainframe_DictLN_TObject;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_string;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_TTimer;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_TQObject;
extern G__linked_taginfo G__jv_mainframe_DictLN_Event_t;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGObject;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGWindow;
extern G__linked_taginfo G__jv_mainframe_DictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGFrame;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGTextButton;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGVerticalFrame;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGMainFrame;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGPictureButton;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGCheckButton;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGLabel;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGListBox;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGTab;
extern G__linked_taginfo G__jv_mainframe_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__jv_mainframe_DictLN_TGNumberEntry;
extern G__linked_taginfo G__jv_mainframe_DictLN_jv_mainframe;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
