//
// File generated by /work/jlab_software/1.3/Linux_Scientific6-x86_64-gcc4.4.7/root/5.34.34/root/bin/rootcint at Mon Apr  4 00:03:58 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIusersdIandreadIjanaviewdIjv_mainframe_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "jv_mainframe_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void jv_mainframe_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_jv_mainframe(void *p);
   static void deleteArray_jv_mainframe(void *p);
   static void destruct_jv_mainframe(void *p);
   static void streamer_jv_mainframe(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::jv_mainframe*)
   {
      ::jv_mainframe *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::jv_mainframe >(0);
      static ::ROOT::TGenericClassInfo 
         instance("jv_mainframe", ::jv_mainframe::Class_Version(), "./src/users/andrea/janaview/jv_mainframe.h", 67,
                  typeid(::jv_mainframe), ::ROOT::DefineBehavior(ptr, ptr),
                  &::jv_mainframe::Dictionary, isa_proxy, 0,
                  sizeof(::jv_mainframe) );
      instance.SetDelete(&delete_jv_mainframe);
      instance.SetDeleteArray(&deleteArray_jv_mainframe);
      instance.SetDestructor(&destruct_jv_mainframe);
      instance.SetStreamerFunc(&streamer_jv_mainframe);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::jv_mainframe*)
   {
      return GenerateInitInstanceLocal((::jv_mainframe*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::jv_mainframe*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr jv_mainframe::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *jv_mainframe::Class_Name()
{
   return "jv_mainframe";
}

//______________________________________________________________________________
const char *jv_mainframe::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::jv_mainframe*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int jv_mainframe::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::jv_mainframe*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void jv_mainframe::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::jv_mainframe*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *jv_mainframe::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::jv_mainframe*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void jv_mainframe::Streamer(TBuffer &R__b)
{
   // Stream an object of class jv_mainframe.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TGMainFrame::Streamer(R__b);
      R__b >> lSource;
      R__b >> lRun;
      R__b >> lEvent;
      R__b >> lObjectType;
      R__b >> lObjectType2;
      R__b >> lObjectValue;
      R__b >> lbObjectTypes;
      R__b >> lbObjects;
      R__b >> lbObjects2;
      R__b >> lbAssociatedObjects;
      R__b >> lbAssociatedToObjects;
      R__b >> lbObjectValues;
      R__b >> fTab;
      R__b >> fCanvas;
      R__b >> fCanvas2;
      R__b >> canvas;
      R__b >> canvas2;
      {
         vector<string> &R__stl =  objtypes;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            string R__t;
            {TString R__str;
             R__str.Streamer(R__b);
             R__t = R__str.Data();}
            R__stl.push_back(R__t);
         }
      }
      {
         vector<void*> &R__stl =  vobjs;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(void*));
         if (R__tcl1==0) {
            Error("vobjs streamer","Missing the TClass object for void*!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            void* R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> timer;
      R__b >> sleep_time;
      R__b >> delayed_object_type_id;
      R__b.CheckByteCount(R__s, R__c, jv_mainframe::IsA());
   } else {
      R__c = R__b.WriteVersion(jv_mainframe::IsA(), kTRUE);
      TGMainFrame::Streamer(R__b);
      R__b << lSource;
      R__b << lRun;
      R__b << lEvent;
      R__b << lObjectType;
      R__b << lObjectType2;
      R__b << lObjectValue;
      R__b << lbObjectTypes;
      R__b << lbObjects;
      R__b << lbObjects2;
      R__b << lbAssociatedObjects;
      R__b << lbAssociatedToObjects;
      R__b << lbObjectValues;
      R__b << fTab;
      R__b << fCanvas;
      R__b << fCanvas2;
      R__b << canvas;
      R__b << canvas2;
      {
         vector<string> &R__stl =  objtypes;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<string>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            {TString R__str((*R__k).c_str());
             R__str.Streamer(R__b);};
            }
         }
      }
      {
         vector<void*> &R__stl =  vobjs;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(void*));
         if (R__tcl1==0) {
            Error("vobjs streamer","Missing the TClass object for void*!");
            return;
         }
            vector<void*>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((void*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << timer;
      R__b << sleep_time;
      R__b << delayed_object_type_id;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void jv_mainframe::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class jv_mainframe.
      TClass *R__cl = ::jv_mainframe::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lSource", &lSource);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lRun", &lRun);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lEvent", &lEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lObjectType", &lObjectType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lObjectType2", &lObjectType2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lObjectValue", &lObjectValue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbObjectTypes", &lbObjectTypes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbObjects", &lbObjects);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbObjects2", &lbObjects2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbAssociatedObjects", &lbAssociatedObjects);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbAssociatedToObjects", &lbAssociatedToObjects);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lbObjectValues", &lbObjectValues);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTab", &fTab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas2", &fCanvas2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*canvas", &canvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*canvas2", &canvas2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "objtypes", (void*)&objtypes);
      R__insp.InspectMember("vector<string>", (void*)&objtypes, "objtypes.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vobjs", (void*)&vobjs);
      R__insp.InspectMember("vector<void*>", (void*)&vobjs, "vobjs.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*timer", &timer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sleep_time", &sleep_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "delayed_object_type_id", &delayed_object_type_id);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_jv_mainframe(void *p) {
      delete ((::jv_mainframe*)p);
   }
   static void deleteArray_jv_mainframe(void *p) {
      delete [] ((::jv_mainframe*)p);
   }
   static void destruct_jv_mainframe(void *p) {
      typedef ::jv_mainframe current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_jv_mainframe(TBuffer &buf, void *obj) {
      ((::jv_mainframe*)obj)->::jv_mainframe::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::jv_mainframe

namespace ROOTDict {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "prec_stl/vector", 49,
                  typeid(vector<string>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<string>

namespace ROOTDict {
   void vectorlEvoidmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEvoidmUgR_Dictionary();
   static void *new_vectorlEvoidmUgR(void *p = 0);
   static void *newArray_vectorlEvoidmUgR(Long_t size, void *p);
   static void delete_vectorlEvoidmUgR(void *p);
   static void deleteArray_vectorlEvoidmUgR(void *p);
   static void destruct_vectorlEvoidmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<void*>*)
   {
      vector<void*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<void*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<void*>", -2, "vector.dll", 0,
                  typeid(vector<void*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEvoidmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<void*>) );
      instance.SetNew(&new_vectorlEvoidmUgR);
      instance.SetNewArray(&newArray_vectorlEvoidmUgR);
      instance.SetDelete(&delete_vectorlEvoidmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvoidmUgR);
      instance.SetDestructor(&destruct_vectorlEvoidmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<void*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<void*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvoidmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<void*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEvoidmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<void*> : new vector<void*>;
   }
   static void *newArray_vectorlEvoidmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<void*>[nElements] : new vector<void*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvoidmUgR(void *p) {
      delete ((vector<void*>*)p);
   }
   static void deleteArray_vectorlEvoidmUgR(void *p) {
      delete [] ((vector<void*>*)p);
   }
   static void destruct_vectorlEvoidmUgR(void *p) {
      typedef vector<void*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<void*>

/********************************************************
* src/users/andrea/janaview/jv_mainframe_Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablejv_mainframe_Dict();

extern "C" void G__set_cpp_environmentjv_mainframe_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("src/users/andrea/janaview/jv_mainframe.h");
  G__cpp_reset_tagtablejv_mainframe_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevjv_mainframe_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* jv_mainframe */
static int G__jv_mainframe_Dict_396_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   jv_mainframe* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new jv_mainframe(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (bool) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) jv_mainframe(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (bool) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->HandleMenu((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoQuit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoNext();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoDelayedSelectObjectType();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoSelectObjectType((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoSelectObject((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoSelectObject2((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoSelectAssociatedObject((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoSelectAssociatedToObject((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoTimer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoDoubleClickAssociatedObject((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->DoDoubleClickAssociatedToObject((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->UpdateInfo(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->UpdateObjectTypeList(*(vector<JVFactoryInfo>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->SelectNewObject((void*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->Redraw((TGFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), (ULong_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddNamedLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]), (ULong_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddNamedLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddNamedLabel((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (ULong_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddCheckButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (ULong_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddCheckButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddPictureButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])), (ULong_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddPictureButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2]))));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddPictureButton((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddSpacer((TGCompositeFrame*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (ULong_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddSpacer((TGCompositeFrame*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddSpacer((TGCompositeFrame*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddSpacer((TGCompositeFrame*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddListBox((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (UInt_t) G__int(libp->para[2]), (ULong_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddListBox((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (UInt_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddListBox((TGCompositeFrame*) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))));
      break;
   case 1:
      G__letint(result7, 85, (long) ((jv_mainframe*) G__getstructoffset())->AddListBox((TGCompositeFrame*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) jv_mainframe::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) jv_mainframe::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) jv_mainframe::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      jv_mainframe::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((jv_mainframe*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) jv_mainframe::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) jv_mainframe::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) jv_mainframe::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__jv_mainframe_Dict_396_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) jv_mainframe::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef jv_mainframe G__Tjv_mainframe;
static int G__jv_mainframe_Dict_396_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (jv_mainframe*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((jv_mainframe*) (soff+(sizeof(jv_mainframe)*i)))->~G__Tjv_mainframe();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (jv_mainframe*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((jv_mainframe*) (soff))->~G__Tjv_mainframe();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* jv_mainframe */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncjv_mainframe_Dict {
 public:
  G__Sizep2memfuncjv_mainframe_Dict(): p(&G__Sizep2memfuncjv_mainframe_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncjv_mainframe_Dict::*p)();
};

size_t G__get_sizep2memfuncjv_mainframe_Dict()
{
  G__Sizep2memfuncjv_mainframe_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancejv_mainframe_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe))) {
     jv_mainframe *G__Lderived;
     G__Lderived=(jv_mainframe*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe),G__get_linked_tagnum(&G__jv_mainframe_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablejv_mainframe_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JVFactoryInfo>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* jv_mainframe */
static void G__setup_memvarjv_mainframe(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe));
   { jv_mainframe *p; p=(jv_mainframe*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->lSource)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lSource=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lRun)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lRun=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lEvent)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lEvent=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lObjectType)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lObjectType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lObjectType2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lObjectType2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lObjectValue)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel),-1,-1,1,"lObjectValue=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbObjectTypes)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbObjectTypes=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbObjects)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbObjects=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbObjects2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbObjects2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbAssociatedObjects)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbAssociatedObjects=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbAssociatedToObjects)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbAssociatedToObjects=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lbObjectValues)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox),-1,-1,1,"lbObjectValues=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTab)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGTab),-1,-1,1,"fTab=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fCanvas)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGVerticalFrame),-1,-1,1,"fCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fCanvas2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGVerticalFrame),-1,-1,1,"fCanvas2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->canvas)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TRootEmbeddedCanvas),-1,-1,1,"canvas=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->canvas2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TRootEmbeddedCanvas),-1,-1,1,"canvas2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->objtypes)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<string>"),-1,1,"objtypes=",0,"nametags of values in object type listbox");
   G__memvar_setup((void*)((long)(&p->vobjs)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR),G__defined_typename("vector<void*>"),-1,1,"vobjs=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TTimer),-1,-1,2,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,2,"sleep_time=",0,"in milliseconds");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"delayed_object_type_id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__jv_mainframe_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarjv_mainframe_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncjv_mainframe(void) {
   /* jv_mainframe */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe));
   G__memfunc_setup("jv_mainframe",1263,G__jv_mainframe_Dict_396_0_1, 105, G__get_linked_tagnum(&G__jv_mainframe_DictLN_jv_mainframe), -1, 0, 4, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h g - - 0 - build_gui", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("HandleMenu",993,G__jv_mainframe_Dict_396_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoQuit",598,G__jv_mainframe_Dict_396_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoNext",594,G__jv_mainframe_Dict_396_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDelayedSelectObjectType",2500,G__jv_mainframe_Dict_396_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectObjectType",1804,G__jv_mainframe_Dict_396_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectObject",1386,G__jv_mainframe_Dict_396_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectObject2",1436,G__jv_mainframe_Dict_396_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectAssociatedObject",2410,G__jv_mainframe_Dict_396_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelectAssociatedToObject",2605,G__jv_mainframe_Dict_396_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoTimer",692,G__jv_mainframe_Dict_396_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDoubleClickAssociatedObject",2891,G__jv_mainframe_Dict_396_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDoubleClickAssociatedToObject",3086,G__jv_mainframe_Dict_396_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleConfigureNotify",2151,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "U 'Event_t' - 0 - event", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpdateInfo",1007,G__jv_mainframe_Dict_396_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - source i - - 0 - run "
"i - - 0 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateObjectTypeList",2040,G__jv_mainframe_Dict_396_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<JVFactoryInfo,allocator<JVFactoryInfo> >' 'vector<JVFactoryInfo>' 1 - facinfo", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectNewObject",1505,G__jv_mainframe_Dict_396_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "Y - - 0 - vobj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Redraw",613,G__jv_mainframe_Dict_396_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGFrame' - 0 - lb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddLabel",745,G__jv_mainframe_Dict_396_0_20, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel), -1, 0, 4, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 - text "
"i - 'Int_t' 0 'kTextLeft' mode k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddNamedLabel",1230,G__jv_mainframe_Dict_396_0_21, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGLabel), -1, 0, 4, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 - text "
"i - 'Int_t' 0 'kTextLeft' mode k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddButton",901,G__jv_mainframe_Dict_396_0_22, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGTextButton), -1, 0, 3, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 - text "
"k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddCheckButton",1379,G__jv_mainframe_Dict_396_0_23, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGCheckButton), -1, 0, 3, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 - text "
"k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddPictureButton",1633,G__jv_mainframe_Dict_396_0_24, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGPictureButton), -1, 0, 4, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 - picture "
"u 'string' - 0 '\"\"' tooltip k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddSpacer",871,G__jv_mainframe_Dict_396_0_25, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGFrame), -1, 0, 4, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame h - 'UInt_t' 0 '10' w "
"h - 'UInt_t' 0 '10' h k - 'ULong_t' 0 'kLHintsCenterX|kLHintsCenterY' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddListBox",974,G__jv_mainframe_Dict_396_0_26, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TGListBox), -1, 0, 4, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame u 'string' - 0 '\"\"' lab "
"h - 'UInt_t' 0 '350' w k - 'ULong_t' 0 'kLHintsLeft|kLHintsTop|kLHintsExpandX|kLHintsExpandY' hints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateGUI",825,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__jv_mainframe_Dict_396_0_28, 85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&jv_mainframe::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__jv_mainframe_Dict_396_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&jv_mainframe::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__jv_mainframe_Dict_396_0_30, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&jv_mainframe::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__jv_mainframe_Dict_396_0_31, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&jv_mainframe::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__jv_mainframe_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__jv_mainframe_Dict_396_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__jv_mainframe_Dict_396_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&jv_mainframe::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__jv_mainframe_Dict_396_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&jv_mainframe::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__jv_mainframe_Dict_396_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&jv_mainframe::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__jv_mainframe_Dict_396_0_39, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&jv_mainframe::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~jv_mainframe", 1389, G__jv_mainframe_Dict_396_0_40, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncjv_mainframe_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaljv_mainframe_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcjv_mainframe_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__jv_mainframe_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR = { "vector<void*,allocator<void*> >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_Event_t = { "Event_t" , 115 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGPictureButton = { "TGPictureButton" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_jv_mainframe = { "jv_mainframe" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR = { "vector<JVFactoryInfo,allocator<JVFactoryInfo> >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JVFactoryInfo,allocator<JVFactoryInfo> >::iterator>" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablejv_mainframe_Dict() {
  G__jv_mainframe_DictLN_TClass.tagnum = -1 ;
  G__jv_mainframe_DictLN_TBuffer.tagnum = -1 ;
  G__jv_mainframe_DictLN_TMemberInspector.tagnum = -1 ;
  G__jv_mainframe_DictLN_TObject.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_string.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_TTimer.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_TQObject.tagnum = -1 ;
  G__jv_mainframe_DictLN_Event_t.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGObject.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGWindow.tagnum = -1 ;
  G__jv_mainframe_DictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGFrame.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGTextButton.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGVerticalFrame.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGMainFrame.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGPictureButton.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGCheckButton.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGLabel.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGListBox.tagnum = -1 ;
  G__jv_mainframe_DictLN_TGTab.tagnum = -1 ;
  G__jv_mainframe_DictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__jv_mainframe_DictLN_jv_mainframe.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablejv_mainframe_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_string);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_Event_t);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGPictureButton);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_TRootEmbeddedCanvas);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_jv_mainframe),sizeof(jv_mainframe),-1,62464,(char*)NULL,G__setup_memvarjv_mainframe,G__setup_memfuncjv_mainframe);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEJVFactoryInfocOallocatorlEJVFactoryInfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__jv_mainframe_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupjv_mainframe_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupjv_mainframe_Dict()");
  G__set_cpp_environmentjv_mainframe_Dict();
  G__cpp_setup_tagtablejv_mainframe_Dict();

  G__cpp_setup_inheritancejv_mainframe_Dict();

  G__cpp_setup_typetablejv_mainframe_Dict();

  G__cpp_setup_memvarjv_mainframe_Dict();

  G__cpp_setup_memfuncjv_mainframe_Dict();
  G__cpp_setup_globaljv_mainframe_Dict();
  G__cpp_setup_funcjv_mainframe_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncjv_mainframe_Dict();
  return;
}
class G__cpp_setup_initjv_mainframe_Dict {
  public:
    G__cpp_setup_initjv_mainframe_Dict() { G__add_setup_func("jv_mainframe_Dict",(G__incsetup)(&G__cpp_setupjv_mainframe_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initjv_mainframe_Dict() { G__remove_setup_func("jv_mainframe_Dict"); }
};
G__cpp_setup_initjv_mainframe_Dict G__cpp_setup_initializerjv_mainframe_Dict;

