from utils import *
Import('env debug')

users_names = getSubdirs('./')

env_plugins=env.Clone()

for user in users_names :
	plugins = getSubdirs(str(user))
	for plugin in plugins:
		print  bcolors.OKGREEN,"Found plugin ",plugin," for user ",user,bcolors.ENDC
		#save the relative dir and the absolute dir
		reldir = str(user)+'/'+str(plugin)
		absdir = Dir('#/src/users/'+reldir).srcnode().abspath	
		#We do not want to increment "at libitum" CPPPATH
		tmp_cpppath=env_plugins['CPPPATH'];	
		env_plugins.Append(CPPPATH=absdir)
		AddROOTdict(env,reldir,absdir);
		user_plugin_src  = Glob(reldir+'/*.cc');
		#print root_dict_src
		#print user_plugin_src
		
		env_plugins.SharedLibrary(source=user_plugin_src,target='#/lib/users/'+user+'_'+plugin,SHLIBPREFIX='',SHLIBSUFFIX='.so')
		env_plugins.Replace(CPPPATH = tmp_cpppath)		
	