from utils import *
Import('env debug et_enable')

plugin_types = getSubdirs('./')


debugSuffix=''
for type in plugin_types:
    plugins = getSubdirs(str(type))
    for plugin in plugins:
        print  bcolors.OKBLUE,"Found plugin ",plugin," for type ",type,bcolors.ENDC
        if (("rootspy" in plugin) and (et_enable == 0)):
            print bcolors.RED,"Ignoring this since no ET support ",bcolors.ENDC
            continue
        #save the relative dir and the absolute dir
        reldir = str(type)+'/'+str(plugin)
        absdir = Dir('#/src/plugins/'+reldir).srcnode().abspath   
        env_plugin=env.Clone()
        env_plugin.Append(CPPPATH=absdir)
   #     env_plugin.Append(LIBS = ['RootSpy'+debugSuffix,'RootSpy-client'+debugSuffix,'cmsgRegex'+debugSuffix,'cmsgxx'+debugSuffix,'cmsg'+debugSuffix,'curl'] )
        
        #Add root dictionaries if necessary
        AddROOTdict(env_plugin,reldir,absdir)
        
        #Compile macros
        AddROOTSpyMacros(env_plugin,reldir,absdir)
        
        
        plugin_src  = Glob(reldir+'/*.cc')
        env_plugin.SharedLibrary(source=plugin_src,target='#/lib/plugins/'+type+'_'+plugin,SHLIBPREFIX='',SHLIBSUFFIX='.so')
          
    